config/routes.rb
Rails.application.routes.draw do
  root 'users#edit'

  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }
  resource :users, only: [:edit, :update]
  resource :documents, only: [:edit, :update] do
    get :document_number
    put :document_number, to: 'documents#update_document_number'
  end
  resources :results, only: [:index]

  post '/users/auth/linkedin', to: 'users/omniauth_callbacks#passthru', as: 'user_linkedin_omniauth_authorize'
  get '/socials/linkedin', to: 'socials#linkedin', as: 'socials_linkedin'
  get 'linked_in', to: 'linked_in#index'
end

app/controllers/documents_controller.rb
class DocumentsController < ApplicationController
  before_action :authenticate_user!

  def edit
    user
  end

  def update
    if user.update_without_password(user_params)
      validator = ImagesValidator.new
      document = validator.valid_document? document_front_side: user.document_front_side.path, document_back_side: user.document_back_side.path
      validation_for_continue = document[:valid?]

      if validation_for_continue
        user.request_logs.create(
          { request_type: :document, request_content: document[:data] }
        )
        @user.complete_step(:document)
        redirect_to :document_number_documents, notice: "Es un documento valido."
      else
        flash[:warning] = "No es un documento valido."
        render :edit
      end


    end
  end

  def document_number
    user
    @document_number = user.request_logs.document.order(created_at: :desc).first.request_content['number'][0..-4]
  end

  def update_document_number
    document = user.request_logs.document.order(created_at: :desc).first
    validation_for_continue = document.request_content['number'].last(3) == user_document_params[:document_number]

    if validation_for_continue
      user.request_logs.create(
        { request_type: :document_number, request_content: user_document_params }
      )

      @user.complete_step(:document_number)
      redirect_to :linked_in, notice: "Número de documento es correcto."
    else
      @document_number = document.request_content['number'][0..-4]

      flash[:warning] = "Número de documento no coincide."
      render :document_number
    end
  end

  private

  def user
    @user ||= current_user
  end

  def user_params
    params.require(:user).permit(:document_front_side, :document_back_side)
  end

  def user_document_params
    params.require(:user).permit(:document_number)
  end
end

app/views/documents/document_number.html.erb
<%= form_tag document_number_documents_path, method: :put do |f| %>

  <fieldset>
    <div class="form-group">
      <%= label_tag :document_number, 'Complete su número de documento', class: 'col-12 control-label no-padding' %>
      <div class="col-12 no-padding">
        <%= @document_number %><%= text_field_tag 'user[document_number]', nil, id: :document_number, class: 'form-control', maxlength: 3, style: 'width: 55px;display: initial;' %>
      </div>
    </div>
  </fieldset>

  <%= submit_tag 'Guardar', class: 'btn btn-md btn-primary' %>
<% end %>

app/views/documents/edit.html.erb
<%= form_for @user, url: documents_path do |f| %>

  <%= render 'shared/form_errors', model: @user %>

  <fieldset>
    <div class="form-group">
      <%= f.label :document_front_side, class: 'col-12 control-label no-padding' %>
      <div class="col-12 no-padding">
        <%= f.file_field :document_front_side, class: 'form-control' %>
      </div>
    </div>
  </fieldset>

  <fieldset>
    <div class="form-group">
      <%= f.label :document_back_side, class: 'col-12 control-label no-padding' %>
      <div class="col-12 no-padding">
        <%= f.file_field :document_back_side, class: 'form-control' %>
      </div>
    </div>
  </fieldset>

  <%= f.submit 'Guardar', class: 'btn btn-md btn-primary' %>
<% end %>