config/routes.rb
Rails.application.routes.draw do
  root 'users#edit'

  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }
  resource :users, only: [:edit, :update]
  resource :documents, only: [:edit, :update] do
    get :document_number
    put :document_number, to: 'documents#update_document_number'
  end
  resources :results, only: [:index]

  post '/users/auth/linkedin', to: 'users/omniauth_callbacks#passthru', as: 'user_linkedin_omniauth_authorize'
  get '/socials/linkedin', to: 'socials#linkedin', as: 'socials_linkedin'
  get 'linked_in', to: 'linked_in#index'
end

app/views/layouts/_header.html.erb
<nav class="sidebar col-xs-12 col-sm-4 col-lg-3 col-xl-2 bg-faded sidebar-style-1">
    <h1 class="site-title"><a href="index.html"><em class="fa fa-rocket"></em> Identity Service</a></h1>

    <a href="#menu-toggle" class="btn btn-default" id="menu-toggle"><em class="fa fa-bars"></em></a>

    <ul class="nav nav-pills flex-column sidebar-nav">
        <% if current_user %>
          <%= link_to '#', class: "nav-link disabled" do %>
            <em class="fa fa-facebook-square"></em> Login
          <% end %>
          <li class="nav-item">
            <%= link_to edit_users_path, class: "nav-link #{'disabled' unless current_user.journey['facebook']}" do %>
              <em class="fa fa-user"></em> Selfie
            <% end %>
          </li>
          <li class="nav-item">
            <%= link_to edit_documents_path, class: "nav-link #{'disabled' unless current_user.journey['selfie']}" do %>
              <em class="fa fa-picture-o"></em> Documento
            <% end %>
          </li>
          <li class="nav-item">
            <%= link_to document_number_documents_path, class: "nav-link #{'disabled' unless current_user.journey['document']}" do %>
              <em class="fa fa-file-text"></em> Número de Documento
            <% end %>
          </li>
          <li class="nav-item">
            <%= link_to linked_in_path, class: "nav-link #{'disabled' unless current_user.journey['document_number']}" do %>
              <em class="fa fa-linkedin-square"></em> LinkedIn
            <% end %>
          </li>
          <li class="nav-item">
            <%= link_to results_path, class: "nav-link #{'disabled' unless current_user.journey['linkedin']}" do %>
              <em class="fa fa-user"></em> Resultado
            <% end %>
          </li>
        <% else %>
          <li class="nav-item">
            <%= link_to root_path, class: "nav-link active" do %>
              <em class="fa fa-user"></em> Login
            <% end %>
          </li>
        <% end %>
    </ul>

    <% if current_user %>
      <%= link_to destroy_user_session_path, method: :delete, class: 'logout-button' do  %>
        <em class="fa fa-power-off"></em> Signout
      <% end %>
    <% end %>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="es">

<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content=".: COSTEROLOS  :.">

    <title>.: Identity Security Service :.</title>

    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>


    <!-- Bootstrap core CSS -->
    <link href="/assets/dist/css/bootstrap.min.css" rel="stylesheet">

    <!--Fonts-->
    <link href="https://fonts.googleapis.com/css?family=Montserrat:300,300i,400,400i,500,500i,600,600i,700,700i" rel="stylesheet">

    <!-- Icons -->
    <link href="/assets/css/font-awesome.css" rel="stylesheet">

    <!-- Custom styles for this template -->
    <link href="/assets/css/style.css" rel="stylesheet">
</head>

<body>
  <div class="container-fluid" id="wrapper">
    <div class="row">

    <%= render partial: '/layouts/header' %>

    <div class="progress">
      <div class="progress-bar bg-danger" role="progressbar" style="width: 25%; height: 1px;background-color: red !important; width: 100%;" aria-valuenow="25" aria-valuemin="0" aria-valuemax="100"></div>
    </div>

    <main class="col-xs-12 col-sm-8 offset-sm-4 col-lg-9 offset-lg-3 col-xl-10 offset-xl-2 pt-3 pl-4">
      <header class="page-header row justify-center">
        <% if user_signed_in? %>
          <div class="col-md-6 col-lg-8">
            <h1 class="float-left text-center text-md-left">¡Bienvenido!</h1>
          </div>
          <div class="dropdown user-dropdown col-md-6 col-lg-4 text-center text-md-right">
            <a class="btn btn-stripped dropdown-toggle" href="https://example.com" id="dropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                <img src="<%= current_user&.image %>" alt="profile photo" class="circle float-left profile-photo" width="50" height="auto">

                <div class="username mt-1">
                    <h4 class="mb-1"><%= current_user&.name %></h4>
                </div>
            </a>

            <div class="dropdown-menu dropdown-menu-right" style="margin-right: 1.5rem;" aria-labelledby="dropdownMenuLink">
              <!-- <a class="dropdown-item" href="#"><em class="fa fa-user-circle mr-1"></em> View Profile</a>
              <a class="dropdown-item" href="#"><em class="fa fa-sliders mr-1"></em> Preferences</a>
              <a class="dropdown-item" href="#"><em class="fa fa-power-off mr-1"></em> Logout</a></div> -->
              <%= link_to destroy_user_session_path, method: :delete, class: 'dropdown-item' do  %>
                  <em class="fa fa-power-off mr-1"></em> Signout
              <% end %>
          </div>
        <% else %>
          <div class="col-md-6 col-lg-8">
            <h1 class="float-left text-center">Inicio de Sesión</h1>
          </div>
        <% end %>
        <div class="clear"></div>
      </header>

      <section class="row">
        <div class="col-sm-12">
        <% flash.each do |key, value| %>
          <div class="alert bg-<%= key == 'warning' ? 'warning' : 'primary' %>" role="alert"><%= value %> <a href="javascript:;" class="float-right close"><em class="fa fa-remove"></em></a></div>
        <% end %>


          <%= yield %>


        </div>
      </section>
    </main>


    </div>
  </div>

  <!-- Bootstrap core JavaScript
  ================================================== -->
  <!-- Placed at the end of the document so the pages load faster -->
  <script src="https://cdnjs.cloudflare.com/ajax/libs/tether/1.4.0/js/tether.min.js" integrity="sha384-DztdAPBWPRXSA/3eYEEUWrWCy7G5KFbe8fFjk5JAIxUYHKkDx6Qin1DkWx51bBrb" crossorigin="anonymous"></script>
  <script src="/assets/js/jquery-3.2.1.min.js"></script>
  <script src="/assets/dist/js/bootstrap.min.js"></script>

  <script src="/assets/js/chart.min.js"></script>
  <script src="/assets/js/chart-data.js"></script>
  <script src="/assets/js/easypiechart.js"></script>
  <script src="/assets/js/easypiechart-data.js"></script>
  <script src="/assets/js/bootstrap-datepicker.js"></script>
  <script src="/assets/js/custom.js"></script>
</body>

</html>